name: tom
channels:
  - defaults
  - menpo
  - conda-forge
  - postelrich
dependencies:
  - python=3.9
  - pip
  - pip:
      - numpy==1.24.*
      - pandas==1.5.*
      - opencv-python==4.7.*
      - ffmpeg==1.4.*
      - ffmpeg-python==0.2.*
      - python-vlc==3.0.*
      - cherrypy==18.8.*
      - pynput==1.7.*
      - pytest==7.1.*
      - git+https://github.com/orcasgit/python-fitbit.git