name: tom
channels:
  - defaults
  - menpo
  - conda-forge
  - postelrich
dependencies:
  - python=3.9
  - pip
  - pip:
      - numpy==1.24.*
      - pandas==2.0.*
      - opencv-python==4.7.*
      - ffmpeg==1.4.*
      - ffmpeg-python==0.2.*
      - python-vlc==3.0.*
      - cherrypy==18.8.*
      - pynput==1.7.*
      - pytest==7.1.*
      - fitbit==0.3.*
      - websockets==10.4.*
      - matplotlib
      - lxml
      - tqdm
      - absl-py
      - easydict
      - pillow
      - ultralytics==8.0.*
      - supervision==0.8.*
      - protobuf==4.23.*
      - openai==0.27.*
      - langchain==0.0.*
      - roboflow==1.0.*
      - googlemaps==4.10.*
      - openrouteservice==2.3.*
      - geographiclib==2.0.*
