name: tom1
channels:
  - defaults
  - menpo
  - conda-forge
  - postelrich
dependencies:
  - python=3.7
  - pip
  - pip:
      - numpy
      - pandas
      - opencv-python==4.1.*
      - ffmpeg==1.4.*
      - ffmpeg-python==0.2.*
      - python-vlc==3.0.*
      - cherrypy==18.8.*
      - pynput==1.7.*
      - pytest==7.1.*
      - git+https://github.com/orcasgit/python-fitbit.git
      - websockets==10.4.*
      - tensorflow==2.3.0
      - matplotlib
      - lxml
      - tqdm
      - absl-py
      - easydict
      - pillow
      - pyyaml