# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exercise_client_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x65xercise_client_data.proto\"\x86\x01\n\x12\x45xerciseClientData\x12\x16\n\x0etotal_distance\x18\x01 \x01(\x01\x12\x17\n\x0f\x63urr_heart_rate\x18\x02 \x01(\x05\x12\x11\n\tavg_speed\x18\x03 \x01(\x01\x12\x11\n\tcurr_time\x18\x04 \x01(\x03\x12\x19\n\x11\x65xercise_duration\x18\x05 \x01(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exercise_client_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EXERCISECLIENTDATA']._serialized_start=31
  _globals['_EXERCISECLIENTDATA']._serialized_end=165
# @@protoc_insertion_point(module_scope)
