# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: type_position_mapping_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n type_position_mapping_data.proto\"\xe5\x02\n\x17TypePositionMappingData\x12$\n\x19running_distance_position\x18\x01 \x01(\x05:\x01\x30\x12%\n\x1arunning_heartrate_position\x18\x02 \x01(\x05:\x01\x35\x12!\n\x16running_speed_position\x18\x03 \x01(\x05:\x01\x36\x12$\n\x19running_duration_position\x18\x04 \x01(\x05:\x01\x37\x12!\n\x15running_time_position\x18\x05 \x01(\x05:\x02\x31\x31\x12\"\n\x17summary_detail_position\x18\x06 \x01(\x05:\x01\x30\x12$\n\x19summary_distance_position\x18\x07 \x01(\x05:\x01\x31\x12!\n\x16summary_speed_position\x18\x08 \x01(\x05:\x01\x32\x12$\n\x19summary_duration_position\x18\t \x01(\x05:\x01\x33')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'type_position_mapping_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TYPEPOSITIONMAPPINGDATA']._serialized_start=37
  _globals['_TYPEPOSITIONMAPPINGDATA']._serialized_end=394
# @@protoc_insertion_point(module_scope)
